CREATE TABLE `bipv_simulations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`name` varchar(255) NOT NULL,
	`technology` varchar(100) NOT NULL,
	`generation` varchar(10) NOT NULL,
	`transparencia` float NOT NULL,
	`eficienciaAjustada` float NOT NULL,
	`areaM2` float NOT NULL,
	`inclinacionFachada` float NOT NULL,
	`azimutFachada` float NOT NULL,
	`kBipv` float NOT NULL,
	`transpositionModel` varchar(20) NOT NULL,
	`latitude` float NOT NULL,
	`longitude` float NOT NULL,
	`energiaAnualKwh` float NOT NULL,
	`energiaAnualKwhM2` float NOT NULL,
	`potenciaPicoW` float NOT NULL,
	`iluminacionPasivaAnualKwh` float NOT NULL,
	`irradianciaReflejadaAnualKwhM2` float NOT NULL,
	`perdidasSoilingAnualKwhM2` float NOT NULL,
	`perdidasTermicasAnualKwhM2` float NOT NULL,
	`iamPromedio` float NOT NULL,
	`soilingPromedio` float NOT NULL,
	`factorTermicoPromedio` float NOT NULL,
	`factorSombraPromedio` float NOT NULL,
	`horasSimuladas` int NOT NULL,
	`produccionMensualKwh` text NOT NULL,
	`iluminacionMensualKwh` text NOT NULL,
	`soilingConfig` text,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `bipv_simulations_id` PRIMARY KEY(`id`)
);
