uploads = []
generated = []

[[outputs]]
id = "S3J5m3o3KB5KkmGl_LiEL"
uri = "file://Adenda_Python_Fotovoltaico.docx"
type = "word_document"
title = "Adenda Python Fotovoltaico — Edición Completa PVsyst"
